services:
    mariadb:
        container_name: inception-mariadb
        build: ./mariadb
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        environments:
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
        restart: unless-stopped
    nginx:
        container_name: inception-nginx
        build: ./nginx
        volumes:
            - wordpress:/var/www/html
        ports:
            - "8443:8443"
        networks:
            - inception
        restart: unless-stopped
    wordpress:
        container_name: inception-wordpress
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - mariadb
        build: ./wordpress
        networks:
            - inception
        env_file:
            - .env
        restart: unless-stopped
volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: ${DATA_DIR}/mariadb
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: ${DATA_DIR}/wordpress
            o: bind
networks:
  inception:
    name: inception
